# Language setting
# en: English
# 语言设置
# zh_CN: 简体中文
language: en
# Default sound effect
# 默认音效
sound: BLOCK_NOTE_BLOCK_HARP
# Default volume
# 默认音量
volume: 1.0
# Default pitch values
# 默认音高
pitch:
  slot0: C1
  slot1: D1
  slot2: E1
  slot3: F1
  slot4: G2
  slot5: A2
  slot6: B2
  slot7: C2
  slot8: D2
# Debug Mode (Default: false)
# Debug 模式开关（默认为false）
debug: false
# DO NOT CHANGE
# 请勿修改
version: 1.0.2
